### ISSUE TITLE
pair_euclidean_layer.cpp

### ISSUE THREAD

**Issue by liuajian** [D-X-Y/Auto-ReID-and-Others#10]
Hello D-X-Y
   I want to modify your pair_euclidean_layer.cpp to a loss layer.
 for example:
 top.size()==1 and output the value of euclidean.
 but the backward_cpu function  cannot be executed，I think this statement may have a problem:  LossLayer<Dtype>::Reshape(bottom,top)
Can you give me some advice on the modification to a loss layer?

**Comment by D-X-Y** [comment]
Would you mind give more details about your implementation?
For your example, https://github.com/D-X-Y/caffe-reid/blob/master/src/caffe/layers/euclidean_loss_layer.cpp  euclidean_loss_layer does what you want. Maybe it would be better to refer to this layer.

**Comment by liuajian** [comment]
#ifndef CAFFE_PAIR_MAHA_LOSS_LAYER_HPP_
#define CAFFE_PAIR_MAHA_LOSS_LAYER_HPP_

#include <vector>

#include "caffe/blob.hpp"
#include "caffe/layer.hpp"
#include "caffe/proto/caffe.pb.h"

#include "caffe/layers/loss_layer.hpp"
//PairMahaLossLayer
namespace caffe {

template <typename Dtype>
class PairMahaLossLayer : public LossLayer<Dtype> {
 public:
  explicit PairMahaLossLayer(const LayerParameter& param)
      : LossLayer<Dtype>(param), diff_() {}
  virtual void LayerSetUp(const vector<Blob<Dtype>*>& bottom,
      const vector<Blob<Dtype>*>& top);
  virtual void Reshape(const vector<Blob<Dtype>*>& bottom,
      const vector<Blob<Dtype>*>& top);

  virtual inline const char* type() const { return "PairMahaLoss"; }
  virtual inline int ExactNumBottomBlobs() const { return 2; }
  virtual inline int ExactNumTopBlobs() const { return 1; }

  virtual inline bool AllowForceBackward(const int bottom_index) const {
    return true;
  }


 protected:
  virtual void Forward_cpu(const vector<Blob<Dtype>*>& bottom,
      const vector<Blob<Dtype>*>& top);
//  virtual void Forward_gpu(const vector<Blob<Dtype>*>& bottom,
//      const vector<Blob<Dtype>*>& top);
  virtual void Backward_cpu(const vector<Blob<Dtype>*>& top,
      const vector<bool>& propagate_down, const vector<Blob<Dtype>*>& bottom);
//  virtual void Backward_gpu(const vector<Blob<Dtype>*>& top,
//      const vector<bool>& propagate_down, const vector<Blob<Dtype>*>& bottom);

Blob<Dtype> diff_;
bool output_labels_;

//add by Ajian Liu
double p_; //M
Blob<Dtype> I_;
Blob<Dtype> Mask_;
Blob<Dtype> Top_data_;
int k_;
int l_;
int change_; //use for change model
};

}  // namespace caffe

#endif  // CAFFE_PAIR_MAHA_LOSS_LAYER_HPP_

**Comment by liuajian** [comment]
#include <vector>

#include "caffe/filler.hpp"
#include "caffe/layers/pair_maha_loss_layer.hpp"
#include "caffe/util/math_functions.hpp"

namespace caffe {
template <typename Dtype>  
void PairMahaLossLayer<Dtype>::Reshape(const vector<Blob<Dtype>*>& bottom,
      const vector<Blob<Dtype>*>& top) {
if (bottom.size() == 2) this->output_labels_ = true; 
else                    this->output_labels_ = false;
  CHECK_EQ(bottom.size(), 2); 
  CHECK_EQ(top.size(), 1);
  CHECK_EQ(bottom[0]->num()%2, 0);//bottom[0]->num()=10 
Top_data_.Reshape(bottom[0]->num()/2,bottom[0]->channels(),bottom[0]->height(),bottom[0]->width());

  if (this->output_labels_) {
    CHECK_EQ(bottom[0]->num(), bottom[1]->num());
    CHECK_EQ(bottom[1]->num(), bottom[1]->count());
    vector<int> shape(1, bottom[0]->num()/2);

  I_.Reshape(shape); //add by Ajian 
  Mask_.Reshape(shape);
  }
diff_.ReshapeLike(Top_data_);

LossLayer<Dtype>::Reshape(bottom, top);
}

template <typename Dtype>  
void PairMahaLossLayer<Dtype>::Forward_cpu(const vector<Blob<Dtype>*>& bottom,
    const vector<Blob<Dtype>*>& top) {
 
  const int count = bottom[0]->count()/2; //75
  const Dtype* A_data = bottom[0]->cpu_data();
  const Dtype* B_data = bottom[0]->cpu_data() + count;
/////////////////////////////////////////
  if (this->output_labels_) {
    const int count_label = bottom[1]->count()/2; //5
    const Dtype* A_label = bottom[1]->cpu_data();
    const Dtype* B_label = bottom[1]->cpu_data() + count_label;
/////////////////////////////////////////////////////////////////////////
k_=0;
for (int i = 0; i < count_label; i++) {
   I_.mutable_cpu_data()[i] = A_label[i] == B_label[i];
       if(I_.mutable_cpu_data()[i]==0)   //add by AJian
        {
           I_.mutable_cpu_data()[i]=-1;   //add by AJian
           k_=k_+1;
         }
    }
//////////////////////////////////////////////////
  }
////////////////////////////////////////////
  caffe_sub(
      count,  
      A_data,
      B_data,
      diff_.mutable_cpu_data());
  caffe_mul(count,diff_.cpu_data(),diff_.cpu_data(),Top_data_.mutable_cpu_data()); 
l_=0;
p_=0;
for(int i=0;i<(bottom[0]->num()/2)*(bottom[0]->channels());i++)
 { 
   if((i+1)%bottom[0]->channels()==0)
     {         
         p_=p_+Top_data_.mutable_cpu_data()[i];
         Mask_.mutable_cpu_data()[l_]=sqrt(p_);     
         p_=0;
         l_=l_+1;
     }
   else
     {      
         p_=p_+Top_data_.mutable_cpu_data()[i];
     }
 }
caffe_mul(bottom[0]->num()/2,I_.cpu_data(), Mask_.mutable_cpu_data(), Mask_.mutable_cpu_data());
//sum_=caffe_cpu_asum(top[1]->count(),Mask_.mutable_cpu_data());
Dtype loss=0;
for(int i=0;i<bottom[0]->num()/2;i++)
{
   loss=loss+Mask_.mutable_cpu_data()[i];
   std::cout<<Mask_.mutable_cpu_data()[i]<<"("<<i<<")"<<" "<<std::endl;
}

top[0]->mutable_cpu_data()[0] = loss;
}

template <typename Dtype>  //four
void PairMahaLossLayer<Dtype>::Backward_cpu(const vector<Blob<Dtype>*>& top,
    const vector<bool>& propagate_down, 
    const vector<Blob<Dtype>*>& bottom) { 
  if (this->param_propagate_down_[0]) {
       const int count = top[0]->count(); //1
       Dtype* diff = bottom[0]->mutable_cpu_diff();//2
       caffe_mul(count, top[0]->cpu_diff(), diff_.cpu_data(), diff);//3
       caffe_cpu_scale(count, Dtype(2), diff, diff); //4
       diff += count;  //5                            
       caffe_mul(count, top[0]->cpu_diff(), diff_.cpu_data(), diff);//6
       caffe_cpu_scale(count, Dtype(-2), diff, diff);//7
   }

#ifdef CPU_ONLY
STUB_GPU(PairMahaLossLayer);
#endif

INSTANTIATE_CLASS(PairMahaLossLayer);
REGISTER_LAYER_CLASS(PairMahaLoss);

}  // namespace caffe

**Comment by liuajian** [comment]
the format of bottom and top is same with center_loss.

**Comment by liuajian** [comment]
Because I have use your reid_data_layer. and the bottom of  euclidean_loss_layer is two features. I want to make the bottom[0] and bottom[1] are features and label respectively. top[0] is the value of euclidean and difference with your pair_euclidean_layer. so I modify your top only. but the backward cannot be executed.

**Comment by liuajian** [comment]
Because I want to keep your bottom,.It is not compatible with the euclidean_loss_layer layer.

**Comment by D-X-Y** [comment]
Would you mind sharing the pair_maha_loss_layer.hpp, all loss layers should inherit LossLayer.

**Comment by liuajian** [comment]
I only modify your euclidean_layer.hpp 
template 
class PairMahaLossLayer : public Layer {
public:

to

template 
class PairMahaLossLayer : public LossLayer {
public:

**Comment by liuajian** [comment]
This is all my .hpp

#ifndef CAFFE_PAIR_MAHA_LOSS_LAYER_HPP_
#define CAFFE_PAIR_MAHA_LOSS_LAYER_HPP_

#include

#include "caffe/blob.hpp"
#include "caffe/layer.hpp"
#include "caffe/proto/caffe.pb.h"

#include "caffe/layers/loss_layer.hpp"
//PairMahaLossLayer
namespace caffe {

template 
class PairMahaLossLayer : public LossLayer {
public:
explicit PairMahaLossLayer(const LayerParameter& param)
: LossLayer(param), diff_() {}
virtual void LayerSetUp(const vector<Blob>& bottom,
const vector<Blob>& top);
virtual void Reshape(const vector<Blob>& bottom,
const vector<Blob>& top);

virtual inline const char* type() const { return "PairMahaLoss"; }
virtual inline int ExactNumBottomBlobs() const { return 2; }
virtual inline int ExactNumTopBlobs() const { return 1; }

virtual inline bool AllowForceBackward(const int bottom_index) const {
return true;
}

protected:
virtual void Forward_cpu(const vector<Blob>& bottom,
const vector<Blob>& top);
// virtual void Forward_gpu(const vector<Blob>& bottom,
// const vector<Blob>& top);
virtual void Backward_cpu(const vector<Blob>& top,
const vector& propagate_down, const vector<Blob>& bottom);
// virtual void Backward_gpu(const vector<Blob>& top,
// const vector& propagate_down, const vector<Blob>& bottom);

Blob diff_;
bool output_labels_;

//add by Ajian Liu
double p_; //M
Blob I_;
Blob Mask_;
Blob Top_data_;
int k_;
int l_;
int change_; //use for change model
};

} // namespace caffe

#endif // CAFFE_PAIR_MAHA_LOSS_LAYER_HPP_
