### ISSUE TITLE
The result of the multi-query on the market dataset in the paper is the question of 81.47 (ResNet-50-Basel)

### ISSUE THREAD

**Issue by liuajian** [D-X-Y/Auto-ReID-and-Others#17]
Dear DXY,
We are having problem in reproducing the multi. query baseline of 81.47 rank1 and 63.95 map, in dataset market1501. We are curious in why your baseline achieve the amazing accuracy much higher than the one published in github by Zhun Zhong et al. Could you mind sharing some insights on reproducing the baseline with us.
Looking forward to hearing from you. 
yours, sincerely
Ajian Liu and Haozhi Huang

**Comment by D-X-Y** [comment]
Closed as caffe-reid is no longer maintained. Please refer this code https://github.com/michuanhaohao/reid-strong-baseline for a much stronger re-id baseline.
